awslabs/amazon-kinesis-video-streams-pic

- .gitignore
- .travis.yml
- CMakeLists.txt
- README.md
- cmake-scripts/libgtest-CMakeLists.txt
- src/client/tst/ClientTestFixture.cpp
- src/client/tst/ClientTestFixture.h
- src/heap/include/com/amazonaws/kinesis/video/heap/Include.h
- src/heap/tst/HeapApiFunctionalityTest.cpp
- src/heap/tst/HeapTestFixture.cpp
- src/mkvgen/tst/MkvgenTestFixture.h
- src/state/tst/StateTestFixture.h
- src/utils/tst/Semaphore.cpp
- src/utils/tst/TimerQueue.cpp
- src/utils/tst/UtilTestFixture.h
- src/view/tst/ViewTestFixture.h
Add everything needed to run tests and generate code coverage
> Add .travis.yml

- src/mkvgen/include/com/amazonaws/kinesis/video/mkvgen/Include.h
- src/mkvgen/src/Include_i.h
- src/mkvgen/src/MkvGenerator.c
- src/mkvgen/tst/AudioCpdParserTest.cpp
> add api to generate aac cpd

- CMake/Dependencies/libgtest-CMakeLists.txt
- CMake/Utilities.cmake
- CMakeLists.txt
> refactor CMakeList. Factor out duplicated code in building dependencies

- src/view/src/ContentView.c
- src/view/tst/ViewApiTest.cpp
> relax content view view item timestamp continuity check

- src/client/src/StreamState.c
- src/client/tst/StateTransitionFunctionalityTest.cpp
- src/client/tst/StreamApiFunctionalityTest.cpp
- src/client/tst/StreamStateTransitionsTest.cpp
- src/client/tst/StreamTokenRotationTest.cpp
> State transitions fix on non-recovery. Unit test coverage

- src/client/src/Client.c
- src/client/src/Stream.c
> log frame state at putKinesisVideoFrame

- src/client/src/Client.c
- src/client/src/Stream.c
- src/client/tst/StreamApiFunctionalityTest.cpp
- src/view/include/com/amazonaws/kinesis/video/view/Include.h
- src/view/src/ContentView.c
- src/view/tst/ViewApiFunctionalityTest.cpp
- src/view/tst/ViewApiTest.cpp
- src/view/tst/ViewDropPolicyFunctionalityTest.cpp
- src/view/tst/ViewTestFixture.cpp
- src/view/tst/ViewTestFixture.h
> change content view to not drop the view item that is currently being tranferred.

- src/client/include/com/amazonaws/kinesis/video/client/Include.h
- src/client/src/Stream.c
> add new isRecoverableStreamError api.

- src/client/include/com/amazonaws/kinesis/video/client/Include.h
- src/client/src/Client.c
- src/client/src/FrameOrderCoordinator.c
- src/client/src/Include_i.h
- src/client/src/InputValidator.c
- src/client/src/InputValidator.h
- src/client/src/Stream.c
- src/client/src/Stream.h
- src/client/src/StreamEvent.c
- src/client/tst/ClientApiFunctionalityTest.cpp
- src/client/tst/ClientApiTest.cpp
- src/client/tst/ClientFunctionalityTest.cpp
- src/client/tst/ClientTestFixture.h
- src/utils/include/com/amazonaws/kinesis/video/utils/Include.h
Issue #46 
Initial work for enhanced stream level metrics. More to follow. Would like to iterate fast on these so this is more of a private PR.
> Enhanced stream and client metrics

- CMake/Utilities.cmake
- CMakeLists.txt
- libkvspic.pc.cmake
- libkvspicClient.pc.cmake
- libkvspicState.pc.cmake
- libkvspicUtils.pc.cmake
Changes:
* Add install steps
* Add pc files
> Enhance build system for users

- src/mkvgen/src/SpsParser.c
- src/mkvgen/src/SpsParser.h
> Cancle checking against hard-coded values for the entire field.

- src/utils/include/com/amazonaws/kinesis/video/utils/Include.h
- src/utils/src/FileLogger.c
- src/utils/src/Include_i.h
- src/utils/tst/FileLogger.cpp
> move file logger into pic

- src/mkvgen/src/SpsParser.c
- src/mkvgen/src/SpsParser.h
- src/utils/src/InstrumentedAllocators.c
1. Get the right nal_reference_bit(2bits)
forbidden_zero_bit (1bit) nal_reference_bit(2bits) nal_unit_type(5bits)
2. Match the print type
> Fix some typos

- src/utils/src/InstrumentedAllocators.c
- src/utils/tst/InstrumentedAllocators.cpp
> Fix re-alloc when the passed pointer is NULL

- src/client/src/Include_i.h
- src/utils/include/com/amazonaws/kinesis/video/utils/Include.h
We will need this functionality in WebRTC so need to expose this instead of duplicating
> Expose EMA macro publictly in PIC Utils

- src/client/include/com/amazonaws/kinesis/video/client/Include.h
- src/client/src/FrameOrderCoordinator.c
- src/client/tst/ClientTestFixture.h
- src/client/tst/MockConsumer.cpp
- src/client/tst/MockConsumer.h
- src/client/tst/MockProducer.cpp
- src/client/tst/MockProducer.h
- src/client/tst/StreamApiFunctionalityScenarioTest.cpp
- src/client/tst/StreamingSession.cpp
- src/client/tst/StreamingSession.h
Issue #https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/issues/128
Adding/adjusting tests for multi-track with EoFR usage.
> Adding multi-track tests with EoFR

- src/client/src/Stream.c
> Resolve deadlock in resetStream

- src/client/src/Client.c
- src/client/src/Stream.c
- src/client/tst/IntermittentProducerAutomaticStreamingTest.cpp
- src/client/tst/StreamFunctionalityTest.cpp
> skip non-key frames after eofr

- src/client/src/Stream.c
Address deadlock putFrame vs callback, streams list lock should NOT be acquired inside a client/stream lock.
> fix potential deadlock

- src/client/src/Stream.c
> Reset client state machine retryCount

- src/mkvgen/src/MkvGenerator.c
> Fixing a minor warning produced by CodeQL

- src/client/src/StreamEvent.c
> Incorrect usage of getUploadInfo API

- .travis.yml
- README.md
> Added README instruction to use devleop, and added develop to travis.yml

- CMake/Dependencies/libgtest-CMakeLists.txt
- CMakeLists.txt
- src/CMakeLists.txt
- src/client/CMakeLists.txt
- src/common/CMakeLists.txt
- src/duration/CMakeLists.txt
- src/heap/CMakeLists.txt
- src/mkvgen/CMakeLists.txt
- src/state/CMakeLists.txt
- src/trace/CMakeLists.txt
- src/utils/CMakeLists.txt
- src/view/CMakeLists.txt
> updated the cmake verison from 2.8 to 3.6.3

- src/client/include/com/amazonaws/kinesis/video/client/Include.h
- src/client/src/Client.c
- src/client/src/Stream.c
- src/client/src/Stream.h
- src/client/tst/StreamApiTest.cpp
- src/client/tst/StreamPutGetTest.cpp
- src/client/tst/StreamRecoveryFunctionalityTest.cpp
- src/mkvgen/include/com/amazonaws/kinesis/video/mkvgen/Include.h
- src/mkvgen/src/Include_i.h
- src/mkvgen/src/MkvGenerator.c
- src/mkvgen/src/MkvStatics.c
- src/mkvgen/tst/MkvgenApiTest.cpp
- src/utils/include/com/amazonaws/kinesis/video/utils/Include.h
- src/utils/src/StackQueue.c
- src/utils/tst/StackQueue.cpp
> KVS Events feature (images/notifications)

- src/client/src/Stream.h
> Missing declaration in Stream.h for putEventMetadata

- src/client/include/com/amazonaws/kinesis/video/client/Include.h
- src/client/src/Stream.c
- src/client/src/Stream.h
- src/client/tst/StreamPutGetTest.cpp
> All events will have a unique L1 TAGS.

- src/client/src/Client.c
- src/utils/include/com/amazonaws/kinesis/video/utils/Include.h
- src/utils/src/ExponentialBackoffRetryStrategy.c
- src/utils/src/Include_i.h
> Expose retry count

- src/client/src/Client.c
- src/state/include/com/amazonaws/kinesis/video/state/Include.h
- src/utils/include/com/amazonaws/kinesis/video/utils/Include.h
- src/utils/src/ExponentialBackoffRetryStrategy.c
- src/utils/tst/ExponentialBackoffUtilsTest.cpp
Incorporating full jitter implementation of exponential backoff algorithm
Incorporating full jitter implementation of exponential backoff algorithm
> Incorporating full jitter implementation of exponential backoff algorithm

- src/state/src/State.c
- src/utils/src/ExponentialBackoffRetryStrategy.c
> Remove check for strategy type

- src/state/src/State.c
> Fix up bad log message

- src/client/include/com/amazonaws/kinesis/video/client/Include.h
- src/client/src/Client.c
- src/client/src/Stream.c
- src/client/src/Stream.h
- src/client/src/StreamState.c
- Add retry count metric for every stream
- Add client level average retry count metric for all streams 
> Retry count Metric

- src/client/src/Stream.c
- src/client/tst/StreamPutGetTest.cpp
> block tags before first cluster, post tags after

- src/mkvgen/include/com/amazonaws/kinesis/video/mkvgen/Include.h
#167 
Give `Frame` a name to match the definition of other `struct`s
> Give Frame a name

- .github/workflows/ci.yml
- CMake/Dependencies/libgtest-CMakeLists.txt
- src/client/include/com/amazonaws/kinesis/video/client/Include.h
- src/client/src/InputValidator.c
- src/client/src/Stream.c
- src/client/src/Stream.h
- src/client/src/StreamState.c
- src/client/tst/AcksFunctionalityTest.cpp
- src/client/tst/CallbacksAndPressuresFunctionalityTest.cpp
- src/client/tst/ClientFunctionalityTest.cpp
- src/client/tst/ClientTestFixture.h
- src/client/tst/IntermittentProducerAutomaticStreamingTest.cpp
- src/client/tst/IntermittentProducerFunctionalityTest.cpp
- src/client/tst/StateTransitionFunctionalityTest.cpp
- src/client/tst/StreamApiFunctionalityScenarioTest.cpp
- src/client/tst/StreamApiFunctionalityTest.cpp
- src/client/tst/StreamFunctionalityTest.cpp
- src/client/tst/StreamRecoveryFunctionalityTest.cpp
- src/client/tst/StreamStoppingFunctionalityTest.cpp
- src/client/tst/TokenRotationFunctionalityTest.cpp
- src/heap/tst/HybridFileHeapTest.cpp
- src/heap/tst/HybridHeapTest.cpp
- src/view/tst/ViewDropPolicyFunctionalityTest.cpp
> Fail create call with flag 1 4 1

- src/client/src/Client.c
> bail out if stream is stopped

- src/client/src/Client.c
- src/client/src/Stream.c
- src/client/src/StreamEvent.c
- src/client/src/StreamState.c
> Add stream name to all log lines

- src/client/src/Stream.c
- src/client/tst/StreamPutGetTest.cpp
> Remove justStartedStreaming flag

- src/utils/src/Time.c
Fix the timestamp generation in milliseconds on the logger
> Test logger

- README.md
> add status of latest CI (remove old travis)

- src/utils/include/com/amazonaws/kinesis/video/utils/Include.h
- src/utils/src/Time.c
- src/utils/tst/FileLogger.cpp
Hotfix release 1.0.1 for logging changes.
> Release 1.0.1 (#208)

- .github/workflows/ci.yml
> Add gcc M1 test

- .github/workflows/ci.yml
- src/utils/src/Threadpool.c
- tst/utils/Thread.cpp
- tst/utils/Threadpool.cpp
Enable TSAN in CI.  Resolve some TSAN failures / cleanup.  Fix test which was failing TSAN due to bad test setup.
> Enable tsan

- .github/workflows/ci.yml
See:  
https://github.com/awslabs/amazon-kinesis-video-streams-pic/commit/e138caebda5788aa2490f4677327b4a8ca7f5bdb
https://github.com/awslabs/amazon-kinesis-video-streams-pic/commit/1287aaac7b3d941c78509be9c45a7944a9476904
> update xcode version due to linker issue in older xcode

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/pr-desc-lint.yml
- Add PR template check to CI and a PR template for this repo.
- To ensure that every PR that is opened has a clear description of the changes. 
- Created a PR template
- Created a CI job to run the description checker
- The same template exists in WebRTC SDK which has been working fine for the past few months.
- CI job in this PR to verify this description.
> Add PR description lint

- src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h
- src/utils/src/FileIo.c
- tst/client/ClientTestFixture.h
- tst/utils/FileIo.cpp
> Add readFile fix on Windows to release
