awslabs/amazon-kinesis-video-streams-pic

src/utils/src/Thread.c
*Issue #, if available: #36 *
- Added logic in THREAD_SLEEP to cater to cases where the sleep time values would be more than the maximum value supported by usleep() / Sleep() (0xffffffff)
- Tested locally with different sleep values for if - else coverage
Resolves #36 
=> [Issue-36] Add logic in thread sleep to handle large sleep values

.travis.yml, src/client/src/Include_i.h, src/client/src/StreamEvent.c, src/client/src/StreamState.c, src/client/tst/ClientTestFixture.h, src/client/tst/MockConsumer.cpp, src/client/tst/MockProducer.cpp, src/client/tst/StateTransitionFunctionalityTest.cpp, src/client/tst/StreamRecoveryFunctionalityTest.cpp
Issue #26 
Adding logic to PIC to not auto-prime on timeout upload handle termination if we have no more data in the buffer to be streamed out.
=> Implementing intermittent producer support in the PIC

src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h, src/utils/include/com/amazonaws/kinesis/video/utils/Include.h, src/utils/src/Allocators.c, src/utils/src/Include_i.h, src/utils/src/InstrumentedAllocators.c, src/utils/tst/InstrumentedAllocators.cpp, src/utils/tst/UtilTestFixture.h
Having an optional compile-time set/reset macros
Minor warning fixes
Unit tests
NOTE: Many of the unit tests overwrite the allocators to do final memory leak tracking. These are Client, Util, C producer, WebRTC Signaling Client unit tests. The instrumented allocator exposed publicly will be useful for the client application debugging any memory leaks. 
The main pattern is to build the application which would use the conditional compilation macros in the commit which in normal compile mode would be no-ops. In case of INSTRUMENTED_ALLOCATORS being set at compile time, the macros will evaluate to the actual calls to the APIs to set the instrumented allocators and re-set them. The pattern of usage will be - when the application starts, it calls SET_INSTRUMENTED_ALLOCATORS() before any …
=> Adding instrumented allocators to util

CMakeLists.txt
Only specify PATHS if we are doing in-tree builds
=> Fix out of tree GTest builds

src/utils/src/String.c, src/utils/tst/FindStringTest.cpp
=> fix strnchr read over buffer when string is not null terminated

src/utils/src/InstrumentedAllocators.c
Instrumented realloc doesn't keep track the memory size that was allocated originally.
=> Fix unupdated size for instrusmented realloc

src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h, src/utils/include/com/amazonaws/kinesis/video/utils/Include.h, src/utils/src/String.c, src/utils/tst/StringSearch.cpp
`STRNSTR` is defined in common def. But, unfortunately, `strnstr` is only defined in BSD. So, to make `STRNSTR` available for all platforms, this PR will add a default implementation in Rabin Karp algorithm.
`STRNSTR` is also needed for this PR, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/600.
=> Add strnstr implementation for non-BSD

src/client/src/Stream.c, src/client/tst/StreamPutGetTest.cpp
Issue: https://github.com/awslabs/amazon-kinesis-video-streams-pic/issues/76
=> Skipping non-key-frames at start.

src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h, src/utils/tst/StringToInteger.cpp
Add sscanf -> SSCANF standard library macro in support of using it in this PR:
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/952
Add sscanf -> SSCANF standard library macro alongside other standard library functions (e.g. printf, snprintf, etc.)
=> Add sscanf to the list of macro-covered standard library functions.

src/client/src/Client.c, src/client/src/Stream.c, src/client/src/StreamEvent.c, src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h, src/heap/include/com/amazonaws/kinesis/video/heap/Include.h, src/heap/src/Common.c, src/heap/src/Common.h, src/heap/src/Heap.c, src/heap/src/HybridFileHeap.c, src/heap/src/HybridFileHeap.h, src/heap/src/HybridHeap.c, src/heap/src/Include_i.h, src/heap/tst/HeapApiFunctionalityTest.cpp, src/heap/tst/HeapApiTest.cpp, src/heap/tst/HeapPerfTest.cpp, src/heap/tst/HeapTestFixture.cpp, src/heap/tst/HeapTestFixture.h, src/heap/tst/HybridFileHeapTest.cpp, src/heap/tst/HybridHeapTest.cpp, src/mkvgen/src/SpsParser.c, src/utils/include/com/amazonaws/kinesis/video/utils/Include.h, src/utils/src/FileIo.c
Issue #23 
Hybrid file backed heap implementation. Have not tested on Windows yet. Will stabilize with Travis run
=> File backed hybrid heap implementation

src/client/include/com/amazonaws/kinesis/video/client/Include.h, src/client/src/Client.c, src/client/src/FrameOrderCoordinator.c, src/client/src/Stream.c, src/client/src/Stream.h, src/client/tst/StreamApiFunctionalityTest.cpp, src/client/tst/StreamApiTest.cpp
This is needed in cases when a higher level application doesn't know about the upstream media source elementary stream NAL packaging format. 
=> Adding ability to set NALu adaptation flags prior starting the stream

src/client/include/com/amazonaws/kinesis/video/client/Include.h, src/client/src/Client.c, src/client/src/Stream.c, src/client/src/Stream.h, src/client/tst/ClientApiTest.cpp
https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/issues/562
Previously, the frame rate reported used getTime() for calculation. The current frame rate truly is indicative of the observed frame rate, which means, it can give an idea of whether the encoder is stable or bursty, however, it is not truly indicative of the elementary frame rate which requires using PTS. This led to adding a new metric called `elementaryFrameRate` that indicates the original streams frame rate and not the rate at which the frames are produced. 
The PR also addresses very high FPS values being observed in multitrack scenario. We only calculate frameRate for video track.
API level unit test is added for Client and Stream metrics. 
TODO: …
=> Fix frame rate calc

CMakeLists.txt, libkvspic.pc.cmake, libkvspicClient.pc.cmake, libkvspicState.pc.cmake, libkvspicUtils.pc.cmake
Description of changes:
As is, this software does not install properly on Red Hat based systems because it has "lib" hardcoded throughout. This pull request adjusts the cmake tooling to use GNUInstallDirs (and the associated CMAKE_INSTALL_LIBDIR/CMAKE_INSTALL_BINDIR) variables. The .pc.in files are also updated to use these variables.
With this change, files are installed into the proper locations on Fedora/Red Hat Enterprise Linux/CentOS/Amazon Linux.
=> use CMAKE_INSTALL_LIBDIR and CMAKE_INSTALL_BINDIR for proper install paths

CMakeLists.txt
Description of changes:
Add support for building the libraries as shared libraries (required for inclusion in Fedora and good practice in most situations). I hardcoded the library version to 0.0.0 and soversion to 0, since amazon-kinesis-video-streams-pic has no versioning (and no releases). If that changes, you will probably want to read those values from a versioning variable.
=> add BUILD_SHARED_LIBS option to build shared libs

src/client/include/com/amazonaws/kinesis/video/client/Include.h, src/mkvgen/include/com/amazonaws/kinesis/video/mkvgen/Include.h
Created audio codec id _enum_ and video codec id _enum_ to provide codec flexibility with Producer SDK. Removed multi-content type as it can be constructed by concatenating two base content types
=> Added codecs enums for video and audio, removed multi-content type

src/mkvgen/include/com/amazonaws/kinesis/video/mkvgen/Include.h
https://github.com/awslabs/amazon-kinesis-video-streams-pic/pull/130
Missed adding back the mulaw-multicontent-type to my previous [PR](https://github.com/awslabs/amazon-kinesis-video-streams-pic/pull/130). Adding it back in this PR for backward compatibility 
=> Adding mulaw multicontent type back

.travis.yml, README.md
=> Added README instruction to use devleop, and added develop to travis.yml

CMakeLists.txt, src/client/src/Stream.c, src/common/include/com/amazonaws/kinesis/video/common/PlatformUtils.h
We do not log the SDK version / git hash. This will be super convenient when debugging issues or when trying to get details from customer on the git version that is being used. When used in producer C, the git hash of producer SDK would be available as an INFO log and when used in WebRTC, the git hash of WebRTC SDK will be available. 
=> Log git hash

src/state/include/com/amazonaws/kinesis/video/state/Include.h, src/state/src/Include_i.h, src/state/src/State.c, src/state/tst/StateApiFunctionalityTest.cpp, src/utils/src/ExponentialBackoffRetryStrategy.c
Updating stepStateMachine to use stateTransitionHookFunc to get next retry wait time for local state retries
We're planning to emit an internal metric on the retry count, this change is required to ensure we're using same exponential backoff logic for adding wait time while transitioning to same OR different states. 
=> Updating stepStateMachine to use stateTransitionHookFunc to get next retry wait time for local state retries

src/client/include/com/amazonaws/kinesis/video/client/Include.h, src/client/src/Client.c, src/client/src/ClientState.c, src/client/src/InputValidator.c, src/client/src/StreamState.c, src/client/tst/ClientTestFixture.cpp, src/client/tst/ClientTestFixture.h, src/state/tst/StateApiFunctionalityTest.cpp, src/state/tst/StateTestFixture.cpp, src/state/tst/StateTestFixture.h, src/utils/include/com/amazonaws/kinesis/video/utils/Include.h, src/utils/src/ExponentialBackoffRetryStrategy.c, src/utils/tst/ExponentialBackoffUtilsTest.cpp
This change includes following - 
- Decoupling retry strategy callbacks from the actual retry strategy
- Adding retry strategy type check before casting retry strategy state
Decoupling retry strategy callbacks from the actual retry strategy, adding retry strategy type check before casting retry strategy state
=> Decoupling retry strategy callbacks from the actual retry strategy, adding retry strategy type check before casting retry strategy state

src/client/src/Client.c
Crate retry strategy after fixing up device info. `fixupDeviceInfo` overwrites deviceInfo.clientInfo and hence we were losing the retry strategy callbacks which are set in configureClientWithRetryStrategy.
=> Create retry strategy after fixing up device info

src/client/include/com/amazonaws/kinesis/video/client/Include.h, src/client/src/ClientState.c, src/client/src/InputValidator.c, src/client/src/StreamState.c, src/client/tst/ClientApiFunctionalityTest.cpp, src/client/tst/ClientApiTest.cpp, src/client/tst/ClientTestFixture.h, src/client/tst/StreamApiTest.cpp, src/client/tst/StreamParallelTest.cpp, src/client/tst/StreamPutGetTest.cpp, src/client/tst/StreamTokenRotationTest.cpp, src/heap/tst/HybridFileHeapTest.cpp, src/mkvgen/tst/MkvgenApiFunctionalityTest.cpp, src/utils/tst/Tags.cpp
- Add configurability for curl call connection and completion timeouts. 
- Fix compiler warning for sprintf in several unit tests
- Add unit test for version (client info)
=> Add completion timeout configurability

src/client/include/com/amazonaws/kinesis/video/client/Include.h, src/client/src/Stream.c, src/client/tst/StreamApiTest.cpp
What was changed?
Added string length limits for event metadata and image prefix as per https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/gs-s3Delivery.html#gs-limits. Also changed the number of supported event metadata pairs as per the public documentation
Why was it changed?
The checks were added to ensure that the string length sanity checks are done early on in the SDK for fail early to avoid back and forth once the metadata is sent and the service rejects it.
How was it changed?
Added length specific macros and related checks in putStreamEventMetadata
Testing:
- Added unit tests for length specific checks
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …
=> Add string length checks for events

src/client/src/StreamEvent.c
When running the sample with H.265, this warning is output, but it doesn't provide details of what the mismatch is, so this resolves that
=> Log the content type when they don't match

src/utils/include/com/amazonaws/kinesis/video/utils/Include.h, src/utils/src/Time.c, src/utils/tst/FileLogger.cpp
Fix millisecond precision in log timestamps.
Earlier: `yyyy-mm-dd HH:MM:SS.ssssss`
After change: `yyyy-mm-dd HH:MM:SS.sss`
Example log line before this change
`2023-08-29 19:29:29.000588 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_BIND_CHANNEL to TURN_STATE_READY`
Example log line after this change
`2023-08-29 19:29:29.588 DEBUG   turnConnectionStepState(): TurnConnection state changed from TURN_STATE_BIND_CHANNEL to TURN_STATE_READY`
=> Fix timestamp ms precision

src/utils/src/Threadpool.c, src/utils/tst/Threadpool.cpp
Threadpool teardown has been changed so that the threads owned by the threadpool will not need to unlock the ThreadData mutex on teardown. This was accomplished by using the terminate atomic bool in place of the locked mutex to indicate that the threadpool has been destroyed.
=> Modify threadpool teardown

src/common/include/com/amazonaws/kinesis/video/common/PlatformUtils.h, src/utils/src/Logger.c
C++ compilers complain about passing string constants to PCHAR so this adds `const` to those so the use of the value is explicit and avoids those issues
=> Use const PCHAR so C++ compilers won't complain about passing string constants

src/client/src/Stream.c, src/client/src/Stream.h, src/client/src/StreamEvent.c, src/client/src/StreamState.c, src/state/src/State.c
Removes the possibility of segfault errors occurring from stack overflows caused by recursive `stepStateMachine()` calls made internally by the stream pointer functions passed as `executeStateFn` to the stream state machine. Implements the following changes:
- Iterating function `iterateStreamStateMachine()` added to the **StreamState** file
- Boolean member `keepIteratingStateMachine` added to the **KinesisVideoStream** struct to track when to keep calling `stepStateMachine()`
- All `stepStateMachine()` calls removed from `executeStateFn` functions
- `iterateStreamStateMachine()` makes `stepStateMachine()` calls as needed based on how was done in the `executeStateFn` functions
- All `stepStateMachine()` calls upon the stream state machine that are outside of `iterateStreamStateMachine()` …
=> Add stream state machine iterator

src/utils/include/com/amazonaws/kinesis/video/utils/Include.h
Utils Library
Some error codes are duplicated. Adjust the ones starting with `LOGGER_` so that they are not duplicate.
https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/57637ea593f4b43c509413a44d993ed08d7f2616/src/utils/include/com/amazonaws/kinesis/video/utils/Include.h#L1292-L1293
https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/57637ea593f4b43c509413a44d993ed08d7f2616/src/utils/include/com/amazonaws/kinesis/video/utils/Include.h#L1457-L1458
=> Utils - Remove duplicate error code

src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h
N/A
* Add a new macro to check for null string or empty string. For readability purposes,
```
if (!IS_NULL_OR_EMPTY(str)) {
```
is better than these two
```
if (!(str == NULL || str[0] == '\0')) {
if (str != NULL && str[0] != '\0') {
```
*Other considerations*
Why don't we just use `strlen(str) > 0`?
1. `strlen` has to traverse the entire string, so it's less efficient than a comparison with the null termination character.
2. If `str` is NULL, using strlen directly may result in undefined behavior.
=> Add is null or empty

src/utils/src/Threadpool.c
In `threadpoolFree` there is a call made to `stackQueueIteratorGetItem` which pass the address of a pointer, but the API expected and returns a UINT64 in this field, this will cause a crash on 32 bit platforms.  For reference similar issue's have been fixed and proper usage can be found elsewhere in PIC:  https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/57637ea593f4b43c509413a44d993ed08d7f2616/src/client/src/Stream.c#L2059-L2062
I've modified this to follow the same pattern.  The CHK for NULL was missing as well if it's null we will seg fault when we try to access `item->dataMutex`.
=> Fix 32 bit crash issue

src/utils/src/Threadpool.c
*Issue #, if available:* 
*Description of changes:* If some threads were created as part of `threadpoolCreate` but less than `minThreads` then clean up will not properly happen for those threads we will not attempt to dequeue and free those tasks that were launched via THREAD_CREATE / DETACH.
=> properly free threadpool if failed to create

src/client/src/Client.c, src/client/src/Include_i.h, src/client/src/Stream.c, src/state/include/com/amazonaws/kinesis/video/state/Include.h, src/state/src/Include_i.h, src/state/src/State.c, tst/state/StateApiTest.cpp
- Added a new API to allow setting tags for state machine logs.
Our SDKs have multiple state machines running at once and it only logs the state in hex, which makes it confusing to understand which state machine transitions are being tracked while debugging. This PR introduces addition of tags when logging state machine transitions in VERBOSE mode to make it easy to understand which state machine transition the logs belong to.
Introduced a new API `createStateMachineWithTag` to pass in a tag. This is mandatory. if not provided the API call would fail.
Earlier:
```
2023-12-28 18:42:08.694 VERBOSE stepStateMachine(): State Machine - Current state: 0x0000000000000001, Next …
```
=> State machine name for logs

src/common/include/com/amazonaws/kinesis/video/common/PlatformUtils.h, src/utils/src/FileLogger.c, src/utils/src/Logger.c
A new log level was introduced in previous version where the value of the level is set to `LOG_LEVEL_PROFILE` (8). LOG_LEVEL_SILENT is set to 7. The SDK has a filtering logic where we log messages with log level greater than the set logLevel. This means, with `LOG_LEVEL_SILENT`, no log messages should be displayed. However, with the new added `LOG_LEVEL_PROFILE`, this breaks when setting log level to `LOG_LEVEL_SILENT` since PROFILE logs would get displayed. This PR fixes the issue.
Testing:
- Tested with WebRTC C sample (which uses PROFILE log level) by setting LOG_LEVEL_SILENT to confirm no logs get displayed if log level is set to 7. Also tested setting every other level.
By submitting this pull request, I confirm that you can use, …
=> Add LOG_LEVEL_SILENT explicitly to avoid PROFILE logs from getting displayed when setting log level to SILENT

src/state/include/com/amazonaws/kinesis/video/state/Include.h, src/state/src/State.c
The intent of using const was to ensure the caller of the API cannot modify the string. However, given the name is set up when invoking `createStateMachineWithName`, even if the caller modifies the name, the state machine name would be unaffected. If invoking `createStateMachineWithName` again, it would create a new state machine object.
=> Remove const in the api definition for getStateMachineName

.github/workflows/ci.yml, CMakeLists.txt, src/client/src/InputValidator.c, tst/client/ClientTestFixture.h
=> Release build

src/utils/src/Threadpool.c, tst/utils/Threadpool.cpp, tst/utils/UtilTestFixture.h
N/A
ThreadData->mutex now wraps all interactions with any threadpool objects, this includes the queue.
As a consequence of having the data mutex locked while waiting on the queue, the threadpool couldn't teardown if an actor was waiting on the queue, so the teardown now pushes wait tasks to the queue in the event of that use case.
Additionally all utils tests were changed so that if a memory leak is detected, it will infinitely wait for the memory leak to end -- resulting in a GHA timeout or a loose actor cleaning up the memory (common race condition specific to tests only).
=> Threadpool tsan

src/view/src/ContentView.c
In cases where the current index has passed the head value we needed a check to reset the index position. Without this check, you would need to iterate until the index had cycled around via integer overflow on a 64-bit integer.
=> Reset current index in case it overflows out of range

src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h, src/utils/src/FileIo.c, tst/client/ClientTestFixture.h, tst/utils/FileIo.cpp
- Fix readFile to work properly for multiline files on Windows
- The readFile was not working as expected from WebRTC C SDK in ASCII mode. To ensure that fread, fseek and ftell works on Windows as expected, compatible functions with expected return values are evaluated and used.
- Use Windows-specific _fseeki64 and _ftelli64 as the traditional fseek and ftell are non-compliant on systems that do not provide the same guarantees as POSIX. On these systems, setting the file position indicator to the end of the file using fseek() is not guaranteed to work for a binary stream, and consequently, the amount of memory allocated may be incorrect, leading to a potential vulnerability …
=> Fix readFile on Windows

CMakeLists.txt, README.md, src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h, src/utils/src/Thread.c, tst/utils/Thread.cpp
Issue #, if available:
Added API to support specifying stack size of threads at time of creation.
Added an ability to specify default stack sizes at compile time.
Libraries that use this asset as a dependency needed to be able to customize their thread stack sizes
New API added, check for default compile time variable.
Old tests passing, new tests added. Additional changes made in upstream libraries using this change that also have tests passing.
=> Add API for specifying thread stack size

.github/workflows/ci.yml, src/client/include/com/amazonaws/kinesis/video/client/Include.h, tst/client/StreamPutGetTest.cpp
- Modified `MAX_FRAGMENT_METADATA_COUNT` to 10 
- Modified actions/checkout@v2 to v4
- Moved from macos-11 to macos-12 as the former has been deprecated
- Changed because that is the limit from the backend
- v2 is an older version and v4 is the latest
- Updated the `MAX_FRAGMENT_METADATA_COUNT`
- Updated the ci.yml
- The CI tests cover this change
=> Change fragment metadata count from 25 to 10

src/client/src/Client.c, src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h, src/heap/src/AivHeap.h
- Include stream name in the log line while stopping stream instead of handle.
- Stream handle value is not informative. Stream name is
- `stopKinesisVideoStreamSync(): [test] Synchronously stopping Kinesis Video Stream` -> this is how it looks now. 
- Earlier: Synchronously stopping Kinesis Video Stream 123345353
- Tested with samples to confirm the change works.
=> Log line fix

.github/workflows/ci.yml, .github/workflows/version-check.yml, CMakeLists.txt
- Adding a new job that will flag if a PR getting merged into master does not have version updated.
- To ensure the CMake file is being changed before cutting a new release.
- To also ensure no changes get merged to master unless a new version is being released.
- Added a new yml file to grep the cmake file for version.
- Tested with develop branch to confirm it works fine. 
=> Version check CI

tst/client/ClientTestFixture.h
N/A
- Unit test. Specifically, "ClientApiTest.client_info_version_test".
- It was failing with the a similar output to this when I cloned it onto my system:
```
[ RUN      ] ClientApiTest.client_info_version_test
[0x00007ff84935e800] [level 4] InputValidator fixupClientInfo(): Connection timeout is invalid...setting to default
[0x00007ff84935e800] [level 4] InputValidator fixupClientInfo(): Completion timeout is invalid...setting to default
[0x00007ff84935e800] [level 4] InputValidator fixupClientInfo(): Invalid ClientInfo version/Users/runner/work/amazon-kinesis-video-streams-pic/amazon-kinesis-video-streams-pic/tst/client/ClientApiTest.cpp:300: Failure
Expected equality of these values: …
```
=> Fix unit test when log level env variable is not set

src/common/include/com/amazonaws/kinesis/video/common/CommonDefs.h
*Issue #, if available:* NA, related to old PR #257
*What was changed?* 
Correct to use "defined" for preprocessor check.
*Why was it changed?* 
Receive a compiler warning with it as is.
`warning: "__aarch64__" is not defined [-Wundef] #if defined __x86_64__ || defined __ppc64__ || __aarch64__
`
*How was it changed?* 
Add the keyword "defined" to the line above.
CI is passing.
=> Correct missing defined in include file
